# Autogenerated wrapper script for GAP_pkg_cohomolo_jll for x86_64-linux-gnu
export calcpres_gap, cohomology_gap, conrun, crrun, egrun, execcmd_gap, extprun, gprun, grrun, matcalc, normrun, nqmrun, nqrun, pcrun, readrels, scrun, selgen, sylrun

JLLWrappers.@generate_wrapper_header("GAP_pkg_cohomolo")
JLLWrappers.@declare_executable_product(calcpres_gap)
JLLWrappers.@declare_executable_product(cohomology_gap)
JLLWrappers.@declare_executable_product(conrun)
JLLWrappers.@declare_executable_product(crrun)
JLLWrappers.@declare_executable_product(egrun)
JLLWrappers.@declare_executable_product(execcmd_gap)
JLLWrappers.@declare_executable_product(extprun)
JLLWrappers.@declare_executable_product(gprun)
JLLWrappers.@declare_executable_product(grrun)
JLLWrappers.@declare_executable_product(matcalc)
JLLWrappers.@declare_executable_product(normrun)
JLLWrappers.@declare_executable_product(nqmrun)
JLLWrappers.@declare_executable_product(nqrun)
JLLWrappers.@declare_executable_product(pcrun)
JLLWrappers.@declare_executable_product(readrels)
JLLWrappers.@declare_executable_product(scrun)
JLLWrappers.@declare_executable_product(selgen)
JLLWrappers.@declare_executable_product(sylrun)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        calcpres_gap,
        "bin/calcpres.gap",
    )

    JLLWrappers.@init_executable_product(
        cohomology_gap,
        "bin/cohomology.gap",
    )

    JLLWrappers.@init_executable_product(
        conrun,
        "bin/conrun",
    )

    JLLWrappers.@init_executable_product(
        crrun,
        "bin/crrun",
    )

    JLLWrappers.@init_executable_product(
        egrun,
        "bin/egrun",
    )

    JLLWrappers.@init_executable_product(
        execcmd_gap,
        "bin/execcmd.gap",
    )

    JLLWrappers.@init_executable_product(
        extprun,
        "bin/extprun",
    )

    JLLWrappers.@init_executable_product(
        gprun,
        "bin/gprun",
    )

    JLLWrappers.@init_executable_product(
        grrun,
        "bin/grrun",
    )

    JLLWrappers.@init_executable_product(
        matcalc,
        "bin/matcalc",
    )

    JLLWrappers.@init_executable_product(
        normrun,
        "bin/normrun",
    )

    JLLWrappers.@init_executable_product(
        nqmrun,
        "bin/nqmrun",
    )

    JLLWrappers.@init_executable_product(
        nqrun,
        "bin/nqrun",
    )

    JLLWrappers.@init_executable_product(
        pcrun,
        "bin/pcrun",
    )

    JLLWrappers.@init_executable_product(
        readrels,
        "bin/readrels",
    )

    JLLWrappers.@init_executable_product(
        scrun,
        "bin/scrun",
    )

    JLLWrappers.@init_executable_product(
        selgen,
        "bin/selgen",
    )

    JLLWrappers.@init_executable_product(
        sylrun,
        "bin/sylrun",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
